/// Flutter icons IconsBraille
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsBraille
///      fonts:
///       - asset: fonts/IconsBraille.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconsBraille {
  IconsBraille._();

  static const _kFontFam = 'IconsBraille';
  static const String? _kFontPkg = null;

  static const IconData braille = IconData(0xf2a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
